---
- name: eclipse | Install eclipse STS Plugin
  command: "/usr/local/eclipse/eclipse -nosplash \
            -application org.eclipse.equinox.p2.director \
            -destination /usr/local/eclipse \
            -repository \
http://download.springsource.com/release/TOOLS/sts4/update/latest/,\
http://download.springsource.com/release/TOOLS/update/e4.12/,\
http://download.eclipse.org/releases/latest \
            -installIU \
org.springframework.ide.eclipse.integration.feature.feature.group,\
org.springframework.ide.eclipse.mylyn.feature.feature.group,\
org.springframework.ide.eclipse.maven.feature.feature.group,\
org.springframework.ide.eclipse.security.feature.feature.group,\
org.springframework.ide.eclipse.aop.feature.feature.group,\
org.springframework.ide.eclipse.ajdt.feature.feature.group,\
org.springframework.ide.eclipse.xml.namespaces.feature.feature.group,\
org.springframework.ide.eclipse.feature.feature.group,\
org.springframework.ide.eclipse.webflow.feature.feature.group,\
org.springframework.ide.eclipse.autowire.feature.feature.group,\
org.springframework.ide.eclipse.boot.dash.feature.feature.group,\
org.springframework.ide.eclipse.batch.feature.feature.group,\
org.springframework.ide.eclipse.data.feature.feature.group,\
org.springframework.ide.eclipse.boot.feature.feature.group,\
org.springsource.ide.eclipse.dashboard.feature.group,\
com.vmware.vfabric.ide.eclipse.tcserver.feature.group,\
org.springframework.boot.ide.main.feature.feature.group,\
org.springframework.tooling.boot.ls.feature.feature.group,\
org.springframework.tooling.cloudfoundry.manifest.ls.feature.feature.group,\
org.springframework.tooling.bosh.ls.feature.feature.group,\
org.springframework.tooling.concourse.ls.feature.feature.group,\
org.springsource.ide.eclipse.commons.quicksearch.feature.feature.group,\
org.springframework.ide.eclipse.boot.dash.feature.feature.group"






# org.springframework.tooling.cloudfoundry.manifest.ls.integration.feature.group,\ no lo encuentra
