---
- name: Playbook java-jee
  hosts: all
  become: true
  vars:
    base_username: java-jee
  tasks:
    # Este rol es obligatorio para para firewall, selinux e instalar software básico para los cursos
    - name: Configuración comun
      include_role:
        name: common
      vars:
        username: "{{ base_username }}"
        # Opciones: [ enforcing | permissive | disabled ] - Si no definimos la variable, se considera disabled.
        common_selinux_state: disabled
        # Variable opcional para cursos que necesiten paquetes de instalación especiales
        extra_software:
          - httpd
    # Puede instalar Oracle JDK 8, o cualquier openjdk, 11 o 14 probados
    - name: Instalación de Java JDK
      include_role:
        name: java
      vars:
        # Solo se soporta openjdk
        java_option: openjdk
        # 1.8.0 y 11
        java_openjdk_version: 11
        # Crea el fichero java_ansible.sh apuntando a la versión de java instalada.
        java_set_java_home: true
        # Versión de java que se va a usar por defecto en la consola shell
        java_set_default: true
    # Instala docker y agrega al usuario al grupo autorizado de usuarios de docker
    - name: Instalación de Docker
      include_role:
        name: docker
      vars:
        docker_authorized_user: "{{ base_username }}"
        docker_compose_install: true
        docker_compose_version: v2.1.1
    # Instalación de mysql y mysql workbench como paquete. 
    - name: Instalación de mysql
      include_role:
        name: mysql
      vars:
        # Ignorado en centos7, ya que solo hay hasta la 8.0.22-1
        mysql_workbench_version: 8.0.24-1
        # opciones probadas 5.7 y 8.0
        mysql_version: 8.0
        mysql_username: "{{ base_username }}"
        mysql_password: "{{ base_username }}"
        mysql_dockerized: true
        mysql_native_shell_client: true
   