- name: Modify mirrors on fedora repositories
  block:
    - name: Modify fedora.repo file
      template:
        src: templates/fedora.repo.conf.j2
        dest: /etc/yum.repos.d/fedora.repo
    - name: Modify fedora-updates.repo file
      template:
        src: templates/fedora.repo.conf.j2
        dest: /etc/yum.repos.d/fedora-updates.repo
  when:
    ansible_distribution == "Fedora"