---
- name: Install mysql
  block:
    - name: Add mysql repo
      yum_repository:
        name: mysql-community
        description: mysql-community
        baseurl: http://repo.mysql.com/yum/mysql-{{ mysql_version }}-community/el/7/$basearch/
        gpgcheck: no
        enabled: yes    
    - name: Disable mysql repo CentOS 8
      shell: dnf module disable -y mysql
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "8"        
    - name: Install MySQL Server
      yum:
        name: mysql-server
        state: installed
      register: install_mysql_centos7
    - name: Install client
      yum:
        name: https://cdn.mysql.com/archives/mysql-workbench/mysql-workbench-community-{{ mysql_workbench_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm
        state: installed
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7"  
  when:
    - ansible_distribution == "CentOS"
    - mysql_version | int < 8 or ansible_distribution_major_version == "7"

- name: Install MySQL CentOS 8
  dnf:
    name: "@mysql"
    state: installed
  register: install_mysql_centos8
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
    - mysql_version | int >= 8

- name: Install client
  dnf:
    name: https://cdn.mysql.com/archives/mysql-workbench/mysql-workbench-community-{{ mysql_workbench_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm
    state: installed
    disable_gpg_check: yes
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: start and enable
  service:
    name: mysqld
    state: started
    enabled: true
  when:
    - ansible_distribution == "CentOS"

- name: change root password for CentOS
  block:
    - name: Change to temp passwd 
      shell: mysql -u root -p"$(grep -oP 'root@localhost. \K.+' /var/log/mysqld.log)" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'MySQL-p4ssw0rd'" --connect-expired-password
    - name: uninstall security component
      shell: mysql -u root -pMySQL-p4ssw0rd -e "uninstall component 'file://component_validate_password';" --connect-expired-password
    - name: set password - {{ mysql_password }}
      shell: mysql -u root -p"MySQL-p4ssw0rd" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}'" --connect-expired-password
  when: 
    - install_mysql_centos7.changed
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - mysql_version | int >= 8

- name: change root password for CentOS
  block:
    - name: Change to temp passwd 
      shell: mysql -u root -p"$(grep -oP 'root@localhost. \K.+' /var/log/mysqld.log)" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'MySQL-p4ssw0rd'" --connect-expired-password
    - name: uninstall security component
      shell: mysql -u root -pMySQL-p4ssw0rd -e "uninstall plugin validate_password;" --connect-expired-password
    - name: set password - {{ mysql_password }}
      shell: mysql -u root -p"MySQL-p4ssw0rd" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}'" --connect-expired-password
  when: 
    - install_mysql_centos7.changed
    - ansible_distribution == "CentOS"
    - mysql_version | int < 8

- name: create root password for centos 8
  shell: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}'" --connect-expired-password
  when: 
    - install_mysql_centos8.changed
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Automatic login
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
  vars:
    my_cnf_user: root
    my_cnf_pass: "{{ mysql_root_password }}"
  when:
    - ansible_distribution == "CentOS"

#
# INSTALL MySQL for Fedora (tested 39 version)
#

- name: Install MySQL on Fedora
  block:        
    - name: Check that mysql-community.repo exists
      stat:
        path: '/etc/yum.repos.d/mysql-community.repo'
      register: stat_result

    - name: Install MySQL repo for Fedora {{ ansible_distribution_major_version }}
      shell: dnf install -y https://dev.mysql.com/get/mysql80-community-release-fc{{ ansible_distribution_major_version }}-2.noarch.rpm
      when: not stat_result.stat.exists

    - name: Install mysql-community-server for Fedora {{ ansible_distribution_major_version }}
      dnf: 
        name: mysql-community-server
        state: present
      register: install_mysql

    - name: start and enable
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Install visual client Workbench (Fedora distros under 39) 
      shell: dnf install -y https://downloads.mysql.com/archives/get/p/8/file/mysql-workbench-community-{{ mysql_workbench_version }}-1.fc{{ ansible_distribution_major_version }}.x86_64.rpm
      when:
        - mysql_client == "workbench"
        - ansible_distribution_major_version | int <= 38

    - name: Install visual client Dbeaver for Fedora
      dnf:
        name: 'https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm'
        state: present
        disable_gpg_check: yes
      when:
        - mysql_client == "dbeaver" or ansible_distribution_major_version == "39"
    
    - name: Install shell client Fedora
      dnf:
        name: community-mysql
        state: present
        disable_gpg_check: yes
      when:
        - mysql_native_shell_client

    - block:
        - name: Change to temp passwd 
          shell: mysql -u root -p"$(grep -oP 'root@localhost. \K.+' /var/log/mysqld.log)" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'MySQL-p4ssw0rd'" --connect-expired-password

        - name: uninstall security component
          shell: mysql -u root -pMySQL-p4ssw0rd -e "uninstall component 'file://component_validate_password';" --connect-expired-password

        - name: set password - {{ mysql_password }}
          shell: mysql -u root -p"MySQL-p4ssw0rd" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}'" --connect-expired-password
      when: install_mysql.changed
    
    - name: Automatic login
      template:
        src: my.cnf.j2
        dest: /root/.my.cnf
      vars:
        my_cnf_user: root
        my_cnf_pass: "{{ mysql_root_password }}"
  when: 
    - ansible_distribution == "Fedora"