- name: Stop firewall
  block:
    - name: Stop firewall service
      service:
        name: "{{ distros[ansible_distribution + ansible_distribution_major_version].firewall_service }}" 
        state: stopped
        enabled: false
  rescue:
  - debug:
      msg: 'Maybe the service does not exist'

- name: set SELinux - {{ common_selinux_state }} 
  selinux:
    policy: targeted
    state: "{{ common_selinux_state }}"
  when: 
    - ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

- name: Install common software
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ base_software + distros[ansible_distribution + ansible_distribution_major_version].software + extra_software }}"
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == "Fedora"

- name: Install common software for Ubuntu
  package:
    name:
      - git
      - telnet
      - wget
      - nano
    state: latest
  when:
    - ansible_distribution == 'Ubuntu'

- name: Enable ntpd
  service:
    name: "{{ distros[ansible_distribution + ansible_distribution_major_version].ntp_service }}" 
    state: started
    enabled: true
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == "Fedora"
    
- name: disable pcscd to avoid multiple root prompts after open apps
  block:
    - name: Stop PCSD
      systemd:
        name: pcscd
        state: stopped
        masked: yes
        enabled: no
      when: ansible_distribution == 'Fedora'
  rescue:
    - debug:
        msg: 'Maybe the service does not exist'
  