##################################
#   _     ___ _   _ _   ___  __  #
#  | |   |_ _| \ | | | | \ \/ /  #
#  | |    | ||  \| | | | |\  /   #
#  | |___ | || |\  | |_| |/  \   #
#  |_____|___|_| \_|\___//_/\_\  #
################################## 
- block:
  - import_tasks: add-code-repository.yml
  - import_tasks: install-visual-studio-code.yml
  when: 
  - ansible_windows_domain is undefined
  
#######################################################
#  __        _____ _   _ ____   _____        ______   #
#  \ \      / /_ _| \ | |  _ \ / _ \ \      / / ___|  #
#   \ \ /\ / / | ||  \| | | | | | | \ \ /\ / /\___ \  #
#    \ V  V /  | || |\  | |_| | |_| |\ V  V /  ___) | #
#     \_/\_/  |___|_| \_|____/ \___/  \_/\_/  |____/  #
#######################################################
- name: Installing Visual Studio Code for Windows
  win_chocolatey:
    name: vscode
    state: present
    timeout: 300
  when: 
  - ansible_windows_domain is defined
  
