---
- name: Change mirror URL
  block:
  - name: Edit yum.repos.d
    become: true
    shell: "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*"
  - name: Add new mirror URL 
    become: true
    shell: "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*"
  when: ansible_distribution == 'CentOS'