---
- name: Upgrade to CentOS Stream
  block:
  - name: Install CentOS release Stream 
    dnf:
      name: centos-release-stream
      state: present
  - name: Swap CentOS repos
    shell: "dnf swap centos-{linux,stream}-repos -y"
  - name: Distro sync
    shell: "dnf distro-sync -y"
  when: ansible_distribution == 'CentOS'