---
- name: Copy Desktop Direct Access
  copy:
    src: /usr/share/applications/google-chrome.desktop
    dest: "{{ chrome_shortcut_path }}/google-chrome.desktop"
    owner: "{{ chrome_owner }}"
    group: "{{ chrome_owner }}"
    mode: 0755
    remote_src: yes